from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
drv_i2c.c
drv_usart.c
hc32_platform.c
""")

CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
